version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cloud_storage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0101
  app:
    build: .
    container_name: app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cloud_storage
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0101
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE=1GB
      - SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE=1GB
      - SERVER_ERROR_INCLUDE_MESSAGE=always
volumes:
  app_postgres_data: